### ISSUE TITLE
CRYSTAL output name should be OUTPUT, not _scheduler-stderr.txt

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#24]
Should be changed in AiiDA somewhere _e.g._ options.metadata.stderr_name

**Comment by blokhin** [comment]
Cross-posting https://github.com/tilde-lab/yascheduler/issues/6

**Comment by blokhin** [comment]
@ansobolev does this reflect a known issue with `Pcrystal` using stderr for logging?

**Comment by ansobolev** [comment]
Yes, otherwise it wouldn't be closed.
