### ISSUE TITLE
development status now parsed from `setup.json`

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/aiida-crystal-dft#60]
In order to remove duplication, we're removing the development status from the aiida plugin registry   and parsing it from the `setup.json` instead.

Just mentioning that on the code registry, the plugin was listed as "beta", while the `setup.json` currently indicates "alpha".
https://github.com/tilde-lab/aiida-crystal-dft/blob/80ddecafc1303cb2204cc2c94a08333453908e1e/setup.json#L9

Feel free to close this issue if you're fine with the "alpha" status - otherwise please update the `setup.json`.

**Comment by blokhin** [comment]
Indeed, it could be considered as already **Beta** now. Many thanks Leo.
