### ISSUE TITLE
Please, let us avoid import star

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#7]
https://github.com/tilde-lab/aiida-crystal/blob/257eab192a56bbda62269fdc525b4e66f7dc7608/aiida_crystal/io/f25.py#L6

**Comment by blokhin** [comment]
https://github.com/tilde-lab/aiida-crystal/blob/257eab192a56bbda62269fdc525b4e66f7dc7608/aiida_crystal/calculations/tests/test_crystal_calc.py#L4

**Comment by blokhin** [comment]
https://github.com/tilde-lab/aiida-crystal/blob/257eab192a56bbda62269fdc525b4e66f7dc7608/aiida_crystal/io/tests/test_f34.py#L6

**Comment by blokhin** [comment]
_etc._

**Comment by ansobolev** [comment]
Can you give any rationale behind it?

**Comment by blokhin** [comment]
In general, import star is considered as an anti-pattern in Python. The reasons are the following. First, it puts a lot of stuff into the namespace and might shadow other object so that you never know about it. Second, you don't know exactly what is being imported (just simply all) and can't easily find from which module a certain thing was imported (readability and maintainability issue). Third, you can't use static checkers to detect errors in your code.
